### PR TITLE
use cm6 keymap instead of event listener

### PR DESCRIPTION
**Pull request by nightwing**
attempt to fix tests for the approach proposed in https://github.com/replit/codemirror-vim/pull/54

### CODE REVIEW

**Review by sergeichestakov — APPROVED** [review]
sweet 🧪

**Comment by nightwing** [comment]
I am actually not sure if we should use this or not.
The only change seems to be the <Esc> key in autocompletion closing the popup instead of exiting the insert mode immediately,  and though this behavior seems more intuitive to me, vim itself exits the insert mode immediately, like we do now.

**Comment by sergeichestakov** [comment]
ahh I see so it takes two clicks of esp to get back to insert mode? agree we should keep current behavior and close the popup + exit insert mode in one click

**Comment by nightwing** [comment]
In that case i guess we should close both of these pull requests, unless we find some other reason to make the switch.

**Pull request closed without merging**
