### PR TITLE
Fix for plugin not receiving events for arrow keys and others

### PR DESCRIPTION
**Pull request by timdown**
The view plugin is currently not receiving `keydown` events for arrow keys, among others. This results in the following issues:

- #15
- #21

The reason this is happening now is that CodeMirror 6's default keymap now adds `preventDefault: true` to the keybinding for each arrow key. It also does this for other keys. See these commits for the default keymap (there are others in other modules):

- [Arrow keys](https://github.com/codemirror/commands/commit/94aca087e7db0b38f62563d2589171fdc847c732#diff-ca92d1afe836a483259dfc56e55ada3e33076f195fd4f2e7a0fd06be4bfa664fL703-L715)
- [Home and End](https://github.com/codemirror/commands/commit/4b12403ec2d4c206d496e556267299f0469fc2b7)
- [Ctrl-b and Mod-i](https://github.com/codemirror/commands/commit/c4abf56a6ba42dcee340af985eb444b45a2ed5a9)

The result is that the `keydown` handler in the view plugin does not receive `keydown` events for these key bindings and therefore CodeMirror's default behaviour happens instead.

This PR fixes the above issues. It does so by having the Vim plugin listen for a `keydown` event in the capturing phase, meaning it receives the event before CodeMirror does, then prevents CodeMirror receiving the event if the plugin has handled it by stopping it propagating. This seems somewhat hacky and brutal but does solve the problem quite neatly, and is the only way I can see to do so without a fairly major rework. It also fixes the following issues, which I think may have existed before the above commits:

- #16
- #17
- #20

### CODE REVIEW

**Comment by nightwing** [comment]
Thank you. This pull request fixes most of the tests that were broken after codemirror api change https://github.com/replit/codemirror-vim/runs/6180651039?check_suite_focus=true

**Comment by timdown** [comment]
I've done a lot of poking around in the CM6 code and I'm having second thoughts about this. It works but I think may be unnecessarily brutal and hard to override, as well as sidestepping the CM6 API. It can be fixed instead by, for example, by wrapping `vimPlugin` on [this line](https://github.com/replit/codemirror-vim/blob/master/src/index.ts#L253) in `Prec.highest()`, although this too is pretty brutal.

The root problem, I'm pretty sure, is that there is what I think is a bug in CM6 that means that including the autocomplete plugin, with `basicSetup` does, sets all keymaps to have highest precedence. Therefore in the example set-up for Vim mode in this repo, the Vim extension receives the `keydown` event after all keymaps, even though the extension is specified first.

I've reported this on the CM forum:

https://discuss.codemirror.net/t/autocomplete-extension-changes-precedence-of-all-keymaps/4662

If this issue is fixed in CM6, this PR can be reverted.

**Comment by timdown** [comment]
Update: it was a CM6 bug and it's [now fixed](https://github.com/codemirror/view/commit/44a4da36761fd78d72799fc60cd254261a3629e6). Once there's a new release of the CM6 view package, this PR should be reverted.

**Comment by sergeichestakov** [comment]
Thanks for the patch and all of the context. I agree we should be using the CM6 API for dom event handlers for better/more predictable interoperability with other plugins. gonna go ahead and revert for now: https://github.com/replit/codemirror-vim/pull/30

I'll hold off on publishing until that commit is released upstream.

**Comment by timdown** [comment]
Fix now published: https://www.npmjs.com/package/@codemirror/view

**Comment by sergeichestakov** [comment]
awesome! published 6.0.1. Lmk if you run into any other issues

**Comment by timdown** [comment]
You might want `"@codemirror/view": "^6.0.3"` in `package.json` maybe?

**Pull request merged**
