### PR TITLE
Fix mac international keyboards

### PR DESCRIPTION
**Pull request by nightwing**
fixes https://github.com/replit/codemirror-vim/issues/56

### CODE REVIEW

**Review by sergeichestakov — APPROVED** [review]
Thanks for the fix! Would be nice to add a test for this

**Comment by huyz** [comment]
What about international characters entered using both the `Shift` and `Option` key?
For example, this is the kind of mapping I have to do right now (before this PR because it hasn't been merged into Obsidian yet):
```
nmap <A-S-ˇ>f :TableFormat
```

On a macOS keyboard this `ˇ` character is generated by holding `Shift+Option`

**Comment by nightwing** [comment]
@huyz what is the expected behavior in this case?

**Comment by huyz** [comment]
I would expect that all I need to do is map:
```vim
nmap ˇf :TableFormat
```
without specifying the redundant `<A-S-` modifiers.

That seems to be correct behavior, but I could be wrong.

**Pull request merged**
