### PR TITLE
"is/as" implementation

### PR DESCRIPTION
**Pull request by kometenstaub**
This implementation is based on the <kbd>(</kbd> and <kbd>)</kbd> sentence movement, but very adapted to <kbd>is</kbd> and <kbd>as</kbd>. Both <kbd>i</kbd> and <kbd>a</kbd> work pretty much like in vim. 

I included that <kbd>as</kbd> only takes the space after a sentence if there is a space before and after the sentence like in vim.
And the one before it if there is no space after the sentence.

### CODE REVIEW

**Comment by kometenstaub** [comment]
I've just seen these two comments:
https://github.com/replit/codemirror-vim/pull/5#issuecomment-1009425871
https://github.com/replit/codemirror-vim/pull/23#issue-1279957649

Does that mean I should PR the changes to the cm5 repo and that I should add test? 

Do you then merge the changes back if they're accepted at the cm5 repo or would you merge this PR?

**Comment by masad-frost** [comment]
If you can do that for now, that'd be great. We'll figure out a better approach moving forward.

**Comment by kometenstaub** [comment]
I'll look into adding tests and making a PR at the cm5 repo then when I find the time.
I'll report back once it's merged.

**Comment by kometenstaub** [comment]
@masad-frost I've tried implementing tests here, but they all fail.

I get the same errors as in this action:
https://github.com/replit/codemirror-vim/runs/7010481423?check_suite_focus=true

I didn't merge the new changes in yet, but there it fails because of the EditorState.

I'll try it in the cm5 repo and see whether the tests are not failing there.

**Comment by kometenstaub** [comment]
I've cloned the codemirror5 repo, but both the normal tests and the vim tests fail (without any changes from my side).

Normal test:

```shell
❯ npm run test

> codemirror@5.65.5 test
> node ./test/run.js

{
  status: 404,
  headers: { server: 'node-static/0.7.9' },
  message: 'Not Found'
}
```

Vim test:

```shell
❯ node ./test/vim_test.js 
/home/user/Gitprojects/codemirror5/test/vim_test.js:1
var Pos = CodeMirror.Pos;
          ^

ReferenceError: CodeMirror is not defined
    at Object.<anonymous> (/home/user/Gitprojects/codemirror5/test/vim_test.js:1:11)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

Node.js v18.3.0
```

I don't know how to fix this/where the issue lies, so I think I cannot make a PR to the cm5 repo. Because the tests in this repo fail as well, I don't see how I am supposed to add them.

I could of course PR my changes to the cm5 repo, but couldn't test the tests I've written.

**Comment by marijnh** [comment]
> If you can do that for now, that'd be great. We'll figure out a better approach moving forward.

Seeing how there's a bunch of patches coming in the past few days, and CM5 is now legacy, *and* I don't know anything about vim and am ill suited to reviewing this stuff, I would be interested in moving to a situation where this repository manages the actual code, and CM5 just pulls it in as a dependency and adds it to its package when building (for backwards compat).

**Comment by kometenstaub** [comment]
@masad-frost The PR to the cm5 repo is merged. How are we going to proceed here?

**Comment by timdown** [comment]
> > If you can do that for now, that'd be great. We'll figure out a better approach moving forward.
> 
> Seeing how there's a bunch of patches coming in the past few days, and CM5 is now legacy, _and_ I don't know anything about vim and am ill suited to reviewing this stuff, I would be interested in moving to a situation where this repository manages the actual code, and CM5 just pulls it in as a dependency and adds it to its package when building (for backwards compat).

That sounds ideal but will require some work to unify the versions of `vim.js` in CM5 and this repository, because they've [diverged](https://github.com/timdown/codemirror-vim/commit/b47cd6a859e081d85e85726690a3e5e93ab705db) (diff from a few days ago).

I'm done with patches for now, at least; I've submitted PRs for all the issues we've found.

**Comment by kometenstaub** [comment]
The changes are already in #33, so I'll close this PR.

**Pull request closed without merging**
